version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24 # Використовуємо Node.js 24, як у твоєму CodeBuild середовищі
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Pre-build step: preparing...
  build:
    commands:
      - echo Build started on `date`
      - npm run build # або інша команда для збірки твого Node.js додатку
  post_build:
    commands:
      - echo Build completed on `date`
      - echo You can add tests or other steps here

artifacts:
  files:
    - '**/*' # все, що треба зберегти як артефакти збірки
